-- Crear tipos de roles
CREATE OR REPLACE TYPE AER_Rol IS OBJECT (
    ROL_id NUMBER,
    ROL_nombre VARCHAR2(50),
    ROL_descripcion VARCHAR2(200),
    ROL_permisos SYS.ODCIVARCHAR2LIST
);
/

-- Crear tabla de roles
CREATE TABLE AER_Roles (
    ROL_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ROL_nombre VARCHAR2(50) NOT NULL,
    ROL_descripcion VARCHAR2(200),
    ROL_permisos SYS.ODCIVARCHAR2LIST,
    ROL_estado VARCHAR2(20) DEFAULT 'activo',
    ROL_fecha_creacion DATE DEFAULT SYSDATE,
    ROL_fecha_actualizacion DATE,
    PRIMARY KEY (ROL_id)
);

-- Insertar roles iniciales
INSERT INTO AER_Roles (ROL_nombre, ROL_descripcion, ROL_permisos) VALUES (
    'ADMIN',
    'Administrador del Sistema',
    SYS.ODCIVARCHAR2LIST(
        'dashboard.view', 'flights.view', 'flights.manage',
        'passengers.view', 'passengers.manage',
        'bookings.view', 'bookings.manage',
        'security.view', 'security.manage',
        'reports.view', 'reports.generate',
        'users.view', 'users.manage', 'roles.manage'
    )
);

INSERT INTO AER_Roles (ROL_nombre, ROL_descripcion, ROL_permisos) VALUES (
    'OPERADOR',
    'Operador de Vuelos',
    SYS.ODCIVARCHAR2LIST(
        'dashboard.view', 'flights.view', 'flights.manage',
        'passengers.view', 'bookings.view', 'bookings.manage',
        'reports.view'
    )
);

INSERT INTO AER_Roles (ROL_nombre, ROL_descripcion, ROL_permisos) VALUES (
    'SEGURIDAD',
    'Agente de Seguridad',
    SYS.ODCIVARCHAR2LIST(
        'dashboard.view', 'security.view', 'security.manage',
        'reports.view'
    )
);

INSERT INTO AER_Roles (ROL_nombre, ROL_descripcion, ROL_permisos) VALUES (
    'CHECK_IN',
    'Agente de Check-in',
    SYS.ODCIVARCHAR2LIST(
        'dashboard.view', 'passengers.view', 'passengers.manage',
        'bookings.view', 'bookings.manage'
    )
);

INSERT INTO AER_Roles (ROL_nombre, ROL_descripcion, ROL_permisos) VALUES (
    'REPORTES',
    'Analista de Reportes',
    SYS.ODCIVARCHAR2LIST(
        'dashboard.view', 'reports.view', 'reports.generate'
    )
);

-- Crear tabla de usuarios con relación a roles
CREATE TABLE AER_Usuario_Roles (
    USR_id NUMBER,
    ROL_id NUMBER,
    PRIMARY KEY (USR_id, ROL_id),
    FOREIGN KEY (USR_id) REFERENCES AER_Usuario(USR_Usuario),
    FOREIGN KEY (ROL_id) REFERENCES AER_Roles(ROL_id)
);

-- Crear procedimiento para asignar roles a usuarios
CREATE OR REPLACE PROCEDURE AER_Asignar_Rol (
    p_usuario_id IN NUMBER,
    p_rol_id IN NUMBER
) IS
BEGIN
    INSERT INTO AER_Usuario_Roles (USR_id, ROL_id)
    VALUES (p_usuario_id, p_rol_id);
END;
/

-- Crear usuarios iniciales
DECLARE
    v_usuario_id NUMBER;
BEGIN
    -- Usuario administrador
    INSERT INTO AER_Usuario (
        USR_email,
        USR_password,
        USR_nombre,
        USR_apellido,
        USR_rol,
        USR_estado,
        USR_fecha_creacion,
        USR_ultimo_login
    ) VALUES (
        'admin@aeropuerto.com',
        '$2a$10$h.zen5xV66/vQSTQwjgyyOEdEePmwYJB3mZGO8fVWdCsCG8iG2Dq2',
        'Administrador',
        'Principal',
        'ADMIN',
        'activo',
        SYSDATE,
        SYSDATE
    ) RETURNING USR_Usuario INTO v_usuario_id;
    
    -- Usuario operador
    INSERT INTO AER_Usuario (
        USR_email,
        USR_password,
        USR_nombre,
        USR_apellido,
        USR_rol,
        USR_estado,
        USR_fecha_creacion,
        USR_ultimo_login
    ) VALUES (
        'operador@aeropuerto.com',
        '$2a$10$3X6V/nKUrqsKjGGALRp/0.6YCJEHjy9W7265NaFk87lPt2vM6eAKa',
        'Operador',
        'Vuelos',
        'OPERADOR',
        'activo',
        SYSDATE,
        SYSDATE
    ) RETURNING USR_Usuario INTO v_usuario_id;
    
    -- Usuario seguridad
    INSERT INTO AER_Usuario (
        USR_email,
        USR_password,
        USR_nombre,
        USR_apellido,
        USR_rol,
        USR_estado,
        USR_fecha_creacion,
        USR_ultimo_login
    ) VALUES (
        'seguridad@aeropuerto.com',
        '$2a$10$JDBDajEdLLEmcCGRjaiT9.zX.KVRVe5h.AMbCnMr0rre5SM958lfS',
        'Agente',
        'Seguridad',
        'SEGURIDAD',
        'activo',
        SYSDATE,
        SYSDATE
    ) RETURNING USR_Usuario INTO v_usuario_id;
    
    -- Usuario check-in
    INSERT INTO AER_Usuario (
        USR_email,
        USR_password,
        USR_nombre,
        USR_apellido,
        USR_rol,
        USR_estado,
        USR_fecha_creacion,
        USR_ultimo_login
    ) VALUES (
        'checkin@aeropuerto.com',
        '$2a$10$qZrURIriV4H9EQ1P5FckFOK4PmULldm9ZgFCBC2q4US16Qa5Z1tYi',
        'Agente',
        'Check-in',
        'CHECK_IN',
        'activo',
        SYSDATE,
        SYSDATE
    ) RETURNING USR_Usuario INTO v_usuario_id;
    
    -- Usuario reportes
    INSERT INTO AER_Usuario (
        USR_email,
        USR_password,
        USR_nombre,
        USR_apellido,
        USR_rol,
        USR_estado,
        USR_fecha_creacion,
        USR_ultimo_login
    ) VALUES (
        'reportes@aeropuerto.com',
        '$2a$10$CTO8hMA2ZcH9wjpW6x3SEeM6cHyewU.HYx.WhoUUvQLSVR6b6.hAC',
        'Analista',
        'Reportes',
        'REPORTES',
        'activo',
        SYSDATE,
        SYSDATE
    ) RETURNING USR_Usuario INTO v_usuario_id;
END;
/
